import google.generativeai as genai
import json
from core.config import GEMINI_API_KEY, GEMINI_MODEL, LABEL_AI_TEXT, LABEL_HUMAN_TEXT 
from core.utils import setup_logger

logger = setup_logger(__name__)

genai.configure(api_key=GEMINI_API_KEY)

def detect_text_gemini(text_content):
    """
    Analyze text for AI generation (ChatGPT, Claude, etc.) using Gemini.
    """
    try:
        model = genai.GenerativeModel(GEMINI_MODEL) # Linked back to stabilized global config
        
        prompt = f"""
        Analyze this text as a forensic linguist. Determine if it was written by a human or generated by an AI Large Language Model (e.g., GPT-4, Claude).
        
        Detection Criteria:
        1. LINGUISTIC VARIABILITY: Does the text have natural 'burstiness' (variation in sentence length and structure)? AI often has uniform rhythm.
        2. UNNATURAL POLISH: Is the text too perfectly structured or overly neutral?
        3. CLICHÉS & PATTERNS: Look for common AI tropes (e.g., 'In conclusion...', 'It is important to note...').
        4. PERPLEXITY: Check if the word choice is statistically too predictable.

        If the text shows unique personal voice, natural errors, or complex human reasoning, classify as 'human'.
        
        Text to analyze:
        ---
        {text_content}
        ---

        Respond ONLY with a JSON object:
        {{
            "classification": "ai" | "authentic",
            "confidence": float (0.0 to 1.0),
            "reason": "Identify specific linguistic patterns. Use 'ai' for LLM-generated text."
        }}
        """

        response = model.generate_content(prompt)
        
        # Parse
        res_text = response.text.strip()
        if "```json" in res_text:
            res_text = res_text.split("```json")[1].split("```")[0].strip()
        elif "```" in res_text:
            res_text = res_text.split("```")[1].split("```")[0].strip()
        
        data = json.loads(res_text)
        classification = str(data.get("classification", "authentic")).lower().strip()
        is_ai = "ai" in classification or "synthetic" in classification
        
        prediction = LABEL_AI_TEXT if is_ai else LABEL_HUMAN_TEXT
        raw_conf = data.get("confidence", 0.5)

        return {
            "prediction": prediction,
            "confidence": round(raw_conf * 100, 2),
            "ai_probability": round(raw_conf, 4) if is_ai else round(1.0 - raw_conf, 4),
            "human_probability": round(1.0 - raw_conf, 4) if is_ai else round(raw_conf, 4),
            "details": {
                "reason": data.get("reason", "Forensic linguistic analysis complete."),
                "model_used": GEMINI_MODEL,
                "raw_probability": raw_conf,
                "determination": classification
            }
        }

    except Exception as e:
        logger.error(f"Gemini Text API error: {e}")
        return {"error": str(e)}
